### ISSUE TITLE
Curse -> Raid Invite Classic throws error

### ISSUE THREAD

**Issue by Kiraan75** [grrttedwards/wow-addon-updater#145]
"Failed to find addon version number for game version: GameVersion.classic, https://www.curseforge.com/wow/addons/raid-invite-classic"

From many curse-addons (which install / update correctly) only THIS one throws the above mentioned error. "pipenv update" done several times. Did I do something wrong?

[addon-updater.log](https://github.com/grrttedwards/wow-addon-updater/files/4705445/addon-updater.log)

**Comment by grrttedwards** [comment]
You’re doing everything right! And great details in the issue, thank you!

The problem here is that that addon only has a “beta” release on Curse. The updater can only find addons that are a full “release” channel version. Sorry about that one.

I’ve considered what it would take to support beta releases, and at the time it didn’t seem worth the trouble. So hopefully the author of that addon can publish a full release version soon.

**Comment by Kiraan75** [comment]
Hi Garrett,Oh I see, that's absolutely ok! Thanks for your investigation and quick response :-)Best regards,René--Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 30.05.20, 13:48 schrieb Garrett Edwards <notifications@github.com>:

   
  You’re doing everything right! And great details in the issue, thank you! 
  The problem here is that that addon only has a “beta” release on Curse. The updater can only find addons that are a full “release” channel version. Sorry about that one. 
  I’ve considered what it would take to support beta releases, and at the time it didn’t seem worth the trouble. So hopefully the author of that addon can publish a full release version soon.

**Comment by grrttedwards** [comment]
Hi, opened #149 for tracking this
