### ISSUE TITLE
ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by Mayo77** [grrttedwards/wow-addon-updater#171]
So i logged in this morning, and tried to update my addons . Got this error: 

`Failed to find addon version number for game version: GameVersion.retail, https://www.curseforge.com/wow/addons/details`

And tried reinstalling python + this program.. and Now i have a different error

`ModuleNotFoundError: No module named 'requests'`

Have i possibly messed up on  a setting or the install, or does this require an update, or does anyone know whats wrong?

Any help would be appreciated - thanks

**Comment by omicron-o** [comment]
It sounds like your installation of wow-addon-updater failed for some reason, pip would have pulled in those dependencies otherwise. Are you using the recommended pipenv installation method? I'm not familiar with that myself, but make sure to check the output of those commands for a better idea of what is going wrong.
