### ISSUE TITLE
Curseforge/Overwolf support

### ISSUE THREAD

**Issue by torkus** [grrttedwards/wow-addon-updater#193]
Quick question for my [list of wow addon managers](https://ogri-la.github.io/wow-addon-managers/), does wow-addon-updater still support Curseforge after the Overwolf [API deprecation](https://mailchi.mp/overwolf/whats-new-with-overwolf-curseforge-november3)?

**Comment by grrttedwards** [comment]
Hi there 👋 So cool to see you in here.

Unfortunately I don’t know the exact status, given that this tool has issues intermittently with Curse anyways, due to Cloudflare script detection. It does not use the API.

https://github.com/grrttedwards/wow-addon-updater/actions/runs/1833722624

The most recent build failed here, but I do not have the time to continue to fight Curse and maintain workarounds. That might mean it’s time to mark my tool as Unmaintained?

**Comment by torkus** [comment]
> That might mean it’s time to mark my tool as Unmaintained?

That will happen naturally or it won't. There are a good handful of addon managers that do use the API that will eventually fail outright I think. Perhaps wow-addon-updater will see some new popularity as one of the few addon managers that can still support it?

There is also https://www.cfwidget.com and https://forge.curseupdate.com that I've seen used. They're closed source from what I can tell but might be the future for those that want to keep on using curseforge.

Anyway, best of luck and thanks for replying.
