### ISSUE TITLE
Extractor not extracting all files

### ISSUE THREAD

**Issue by Ghosthree3** [grrttedwards/wow-addon-updater#49]
There's a severe issue at the moment causing most addons to be broken upon installation, not every directory inside the zip is being extracted.

Example: WeakAuras-2.14.1.zip contains the following four directories,
WeakAuras
WeakAurasModelPaths
WeakAurasOptions
WeakAurasTemplates

After the latest few commits I finally decided to use the fork full time (I didn't want to break what was 'working' so waited until the clean extract PR), but did backup my old AddOns directory first. The old directory had 194 directories inside it, the new, clean one, has 77.

My guess is that only the first encountered directory is being placed, then the function ends, but it's not alphabetical because...

This is a list of every directory contained within Altoholic+v8.2.001.zip:
Altoholic
Altoholic_Achievements
Altoholic_Agenda
Altoholic_Characters
Altoholic_Grids
Altoholic_Guild
Altoholic_Search
Altoholic_Summary
DataStore
DataStore_Achievements
DataStore_Agenda
DataStore_Auctions
DataStore_Characters
DataStore_Containers
DataStore_Crafts
DataStore_Currencies
DataStore_Garrisons
DataStore_Inventory
DataStore_Mails
DataStore_Pets
DataStore_Quests
DataStore_Reputations
DataStore_Spells
DataStore_Stats
DataStore_Talents

This is the only directory that actually made it to the AddOns directory:
DataStore_Stats

**Comment by grrttedwards** [comment]
Agh. Not good. Sorry for breaking those addons. All my tests only include one top-level folder in the archive... I guess that assumption is wrong!

**Comment by grrttedwards** [comment]
This points out that the extractor really needs to be refactored -- different sites package their addons completely differently... makes it difficult to have one method handle all that.

**Comment by grrttedwards** [comment]
I closed this with #51. Sorry for the interruption. I now test that situation, too.

**Comment by grrttedwards** [comment]
@Ghosthree3 in case you were wondering, you were almost spot-on with the bug. 

First, I made a wrong assumption that one addon archive will only contain one top level folder. Then, the code tries to figure out what is the “top most” level folder, by either finding the actual first folder, or by finding the first zip archive member and splitting on the `/` character.

Apparently zip files may not actually contain a top-level folder entry, depending on the platform that zipped it... overall it’s a painful mess.

So, in combination, those two things only extracted the lucky entry in the zip that it thought was the “top level” folder, which is why only one folder was extracted.
