### ISSUE TITLE
Addons with no release version on CurseForge fail to download at all

### ISSUE THREAD

**Issue by Ghosthree3** [grrttedwards/wow-addon-updater#63]
Very simply, if an addon only has beta releases (and as such no release on the main page) it won't download at all, throwing 'Failed to find addon version number for game version: GameVersion.<version>'.

Examples:
Retail: https://www.curseforge.com/wow/addons/healerstatweights
Classic: https://www.curseforge.com/wow/addons/atlaslootclassic

I'm not really sure what can be done about this other than using the old download method, which would be unable to tell retail and classic versions apart, simply grabbing the latest file and putting it in the addons directory.
However, I find it unlikely that any addon with _only_ beta releases will have both retail and classic versions. More likely it is niche and only focused on one version, so the risk with the old behavior could simply be taken.

**Comment by grrttedwards** [comment]
I'm not really sure I want to get into handling this kind of situation. The example you linked for healerstatweights hasn't been updated since April of this year, so it seems unlikely that it would be "updated" frequently as what makes this utility useful.

I would *much* prefer to have a defined behavior if it means not guessing what it is going to pull, or introducing more fragile HTML parsing.

The atlaslootclassic example I actually ran into myself, but that's also another relatively low likelihood scenario where the addon authors are using the pre-release versions on Curse.

In any event, you can work around these by using the WoWInterface mirror for that addon (https://www.wowinterface.com/downloads/info25185-AtlasLootClassic.html) or by going straight to the GitHub source linked on the Curse page and adding these to your config:
```
https://github.com/Hoizame/AtlasLootClassic|AtlasLootClassic
https://github.com/Hoizame/AtlasLootClassic|AtlasLootClassic_Collections
https://github.com/Hoizame/AtlasLootClassic|AtlasLootClassic_Crafting
https://github.com/Hoizame/AtlasLootClassic|AtlasLootClassic_DungeonsAndRaids
https://github.com/Hoizame/AtlasLootClassic|AtlasLootClassic_Factions
https://github.com/Hoizame/AtlasLootClassic|AtlasLootClassic_Options
https://github.com/Hoizame/AtlasLootClassic|AtlasLootClassic_PvP
```

**Comment by grrttedwards** [comment]
@Ghosthree3 Good news for atlasloot, is that they have promoted a main release version on Curse.
`atlaslootclassic v1.1.11-classic`

**Comment by grrttedwards** [comment]
Closing this per my reasoning above.
