### ISSUE TITLE
Addon Updater Can't Find Directory

### ISSUE THREAD

**Issue by DarkVirtue** [grrttedwards/wow-addon-updater#79]
Versions:
OS: Kubuntu 19.04
Python: 3.7.3
Pip: 18.1
Pipenv: 2018.11.26

I've just set up the updater script for the first time. The modules and pipenv installs went fine, no errors. I populated the addons.txt file.

When I try to run the updater, it tells me it can't find the addon directory no matter what directory I try to give it in the config file.
The path to my WoW install is:
/home/<username>/Games/battlenet/drive_c/Program Files (x86)/World of Warcraft/_retail_/Interface/AddOns
I've tried:
* "double quoting the path"
* 'single quoting the path'
* escaping\ the\ spaces\ and\ symbols
* pointing the config -> to a cleanly-named symlink to the addons directory
* mount --binding the addons directory to a cleanly-named point
* creating a completely new directory, like /tmp/addons

In every case, I get the same error. Am I missing something? Do I need to tweak my environment somehow?

**Comment by grrttedwards** [comment]
Hi @DarkVirtue I don't personally have a linux machine to test this on (only Windows, and I know from another user that the linux subsystem in windows is also not working completely).

I hope someone can help you out here. I do believe other users are on *nix systems and are able to use the tool. You seem to be pretty competent with your machine, but I do still want to ask: is the path you're using supposed to have the double slash in `/home//Games/...` 😝 ?

Lastly, I believe in the config you need to put spaces around the key-value delimiter (the `=` sign).
Like how in the default config it has 
```
WoW Addon Location = C:\Program Files (x86)\World of Warcraft\_retail_\Interface\AddOns
```
with a space on each side of the ` = `. Just double check that. Otherwise I don't have a whole lot of wisdom for you :(

**Comment by DarkVirtue** [comment]
Thanks for the input. I appreciate you paid close attention to what I had written. The // is GitHub trying to format the text - I had written "username" there with angle brackets on either side and GitHub thought I was trying to open a tag. It's the same reason "retail" is italicized - the markup for italics is underscores on either side. I should have used back-ticks to mark it as code.

I do have the spaces around the = in the config, so that's not it.

The kicker is that it actually works just fine on my laptop, which is running the same OS, Python version, etc. But my laptop can't run WoW :P

So there's some subtle difference between my laptop and main computer. I know Linux pretty well, but Python's new to me, so I'm not sure where the snag could be.

**Comment by grrttedwards** [comment]
Ah I see. Yeah that's really weird. I don't imagine it's a Python problem -- at least I hope not, the `os.path` std lib should be pretty solid.

The only other thing I can possibly think of is maybe an accidental stray line-ending character? Like if the path string is `/your/path/AddOns\r\n` and it reads that `\r` as a "normal" invisible character since that's not the normal line-end on your platform? Dunno.

**Comment by DarkVirtue** [comment]
I just tried it again now and removed the single-quotes I had tested with last. The path is unescaped and unquoted, and it worked just fine. I may have been overthinking it when I set it up the first time.

Thanks for the help, I really appreciate it!

**Comment by minikN** [comment]
I've had exactly the same problem. Thanks.
